# Define a compiler and a linker.
CC=gcc

# Name of the library to be created.
TARGET=libccsds123

# General compiler flags.
CCFLAGS=-g -Wall -I./inc

# Linking flags.
LINK_FLAGS=-lm

.PHONY: all clean

all: $(TARGET)